package com.voxit.app

import android.content.Context
import android.net.Uri
import android.provider.OpenableColumns
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import com.voxit.app.domain.*
import com.voxit.app.live.LiveProtectionService
import com.voxit.app.live.LiveProtectionStore
import com.voxit.app.live.LiveProtectionViewModel
import com.voxit.app.ui.theme.*
import kotlinx.coroutines.delay

class MainActivity : ComponentActivity() {
    private var openLiveProtection by mutableStateOf(false)
    override fun onCreate(savedInstanceState: android.os.Bundle?) {
        super.onCreate(savedInstanceState)
        openLiveProtection = intent?.action == LiveProtectionService.ACTION_OPEN
        enableEdgeToEdge()
        setContent { VoxITTheme { VoxITApp(openLiveProtection, onOpenLiveHandled = { openLiveProtection = false }) } }
    }

    override fun onNewIntent(intent: android.content.Intent) { super.onNewIntent(intent); setIntent(intent); if (intent.action == LiveProtectionService.ACTION_OPEN) { openLiveProtection = true; LiveProtectionStore.requestOpenLive() } }
    override fun onStart() { super.onStart(); LiveProtectionStore.appVisible = true }
    override fun onStop() { LiveProtectionStore.appVisible = false; super.onStop() }
}

private object Route { const val Splash="splash"; const val Onboarding="onboarding"; const val Home="home"; const val Upload="upload"; const val RealResult="real-result"; const val Live="live"; const val Demo="demo"; const val Result="result"; const val Transcript="transcript"; const val History="history"; const val Privacy="privacy"; const val Settings="settings" }

private class VoxViewModel : ViewModel() {
    var demoMode by mutableStateOf(false); var selectedScenario by mutableStateOf(DemoScenario.scenarios.first()); var selectedFile by mutableStateOf<FileInfo?>(null)
    var notificationEnabled by mutableStateOf(true); var vibrationEnabled by mutableStateOf(true); var bubbleEnabled by mutableStateOf(false); var saveTranscript by mutableStateOf(false); var alertThreshold by mutableIntStateOf(70)
    fun selectFile(context: Context, uri: Uri) { selectedFile = context.fileInfo(uri) }
}

@Composable private fun VoxITApp(openLiveProtection: Boolean = false, onOpenLiveHandled: () -> Unit = {}, vm: VoxViewModel = viewModel { VoxViewModel() }) {
    val nav = rememberNavController()
    val context = LocalContext.current
    val applicationContext = context.applicationContext
    val phase2ViewModel: com.voxit.app.phase2.Phase2ViewModel = viewModel { com.voxit.app.phase2.Phase2ViewModel(applicationContext) }
    val modelCatalog by phase2ViewModel.modelCatalog.collectAsState()
    val liveViewModel: LiveProtectionViewModel = viewModel { LiveProtectionViewModel(applicationContext) }
    val liveState by liveViewModel.state.collectAsState()
    val currentRoute = nav.currentBackStackEntryAsState().value?.destination?.route
    var globalAlertShown by rememberSaveable { mutableLongStateOf(0L) }
    LaunchedEffect(openLiveProtection) { if (openLiveProtection) { nav.navigate(Route.Live) { launchSingleTop = true }; onOpenLiveHandled() } }
    LaunchedEffect(Unit) { LiveProtectionStore.openLiveRequests.collect { nav.navigate(Route.Live) { launchSingleTop = true } } }
    if (currentRoute != Route.Live && liveState.status == com.voxit.app.live.LiveSessionStatus.ALERT && liveState.alertSequence > globalAlertShown) {
        AlertDialog(
            onDismissRequest = { globalAlertShown = liveState.alertSequence; liveViewModel.continueMonitoring() },
            title = { Text("Verify before sharing") },
            text = { Text(LiveProtectionService.ALERT_TEXT) },
            confirmButton = { Button(onClick = { globalAlertShown = liveState.alertSequence; nav.navigate(Route.Live) { launchSingleTop = true } }) { Text("Review Live Protection") } },
            dismissButton = { Column(horizontalAlignment = Alignment.End) {
                OutlinedButton(onClick = { globalAlertShown = liveState.alertSequence; liveViewModel.continueMonitoring() }) { Text("Continue Monitoring") }
                OutlinedButton(onClick = { globalAlertShown = liveState.alertSequence; liveViewModel.pause() }) { Text("Pause") }
                OutlinedButton(onClick = { globalAlertShown = liveState.alertSequence; liveViewModel.stop() }) { Text("Stop Monitoring") }
                OutlinedButton(onClick = { context.startActivity(android.content.Intent(android.content.Intent.ACTION_DIAL)) }) { Text("Verify Caller") }
                OutlinedButton(onClick = { context.startActivity(android.content.Intent(android.provider.Settings.ACTION_SOUND_SETTINGS)) }) { Text("Open Phone Controls") }
            } },
        )
    }
    NavHost(navController = nav, startDestination = Route.Splash) {
        composable(Route.Splash) { SplashScreen { nav.navigate(Route.Onboarding) { popUpTo(Route.Splash) { inclusive=true } } } }
        composable(Route.Onboarding) { OnboardingScreen({ nav.navigate(Route.Home) { popUpTo(Route.Onboarding) { inclusive=true } } }, { nav.navigate(Route.Privacy) }, { nav.navigate(Route.Home) { popUpTo(Route.Onboarding) { inclusive=true } } }) }
        composable(Route.Home) { HomeScreen(vm, nav) }; composable(Route.Upload) { Phase2UploadScreen(phase2ViewModel, { nav.popBackStack() }, { nav.navigate(Route.RealResult) }) }; composable(Route.RealResult) { Phase2RealResultScreen(phase2ViewModel) { nav.popBackStack() } }; composable(Route.Live) { LiveProtectionScreen(liveViewModel, { nav.popBackStack() }, { nav.navigate(Route.Upload) }, vm.bubbleEnabled, { vm.bubbleEnabled = it }, vm.notificationEnabled, vm.vibrationEnabled, vm.alertThreshold, modelCatalog.selectedModelId) }; composable(Route.Demo) { DemoScreen(vm, nav) }
        composable(Route.Result) { ResultScreen(vm.selectedScenario, nav) }; composable(Route.Transcript) { TranscriptScreen(vm.selectedScenario, nav) }; composable(Route.History) { HistoryScreen(nav) }; composable(Route.Privacy) { PrivacyScreen(nav, phase2ViewModel) }; composable(Route.Settings) { SettingsScreen(vm, nav, phase2ViewModel) }
    }
}

@Composable private fun SplashScreen(onDone: () -> Unit) {
    LaunchedEffect(Unit) { delay(1300); onDone() }
    Box(Modifier.fillMaxSize().background(Navy).padding(32.dp), contentAlignment=Alignment.Center) { Column(horizontalAlignment=Alignment.CenterHorizontally) { ShieldMark(Modifier.size(104.dp)); Spacer(Modifier.height(28.dp)); Wordmark(44.sp); Spacer(Modifier.height(8.dp)); Text("Trust Every Voice", color=SignalMuted, fontSize=18.sp); Spacer(Modifier.height(36.dp)); Text("Privacy-first voice integrity", color=SignalMuted, fontSize=13.sp) } }
}

@Composable private fun OnboardingScreen(onContinue:()->Unit,onPrivacy:()->Unit,onSkip:()->Unit)=PageScaffold("Welcome",null) {
    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(24.dp), verticalArrangement=Arrangement.spacedBy(18.dp)) { ShieldMark(Modifier.size(64.dp)); Wordmark(34.sp); Text("Voice safety, with clear limits.",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold); InfoPanel("VoxIT analyses audio for possible manipulation and scam indicators. Results are warnings, not proof."); PrivacyPoint("No silent recording","VoxIT never secretly records calls. You start Live Protection yourself."); PrivacyPoint("Android limitation","Standard Android apps cannot directly access protected cellular-call audio. Live analysis uses your microphone and works best with speakerphone enabled."); PrivacyPoint("Your data","Audio and transcripts remain on this device by default."); Button(onClick=onContinue,modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Continue")}; OutlinedButton(onClick=onPrivacy,modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Privacy Policy")}; OutlinedButton(onClick=onSkip,modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Skip for Now")} }
}

@Composable private fun HomeScreen(vm:VoxViewModel,nav:NavHostController)=PageScaffold("Home",null) {
    LazyColumn(Modifier.fillMaxSize().padding(horizontal=20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)) { item { Spacer(Modifier.height(8.dp)); Row(verticalAlignment=Alignment.CenterVertically){Wordmark(32.sp);Spacer(Modifier.width(12.dp));StatusPill("Detector: not installed",Amber)} }; item { Text("Protect the conversation, not just the call.",style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.SemiBold) }; if(vm.demoMode)item { DemoBadge() }; item { InfoPanel("Model status: unavailable • Privacy-first processing stays on this device by default.") }; item { PrimaryAction("Upload Recording","Choose an audio file using Android's secure file picker."){nav.navigate(Route.Upload)} }; item { PrimaryAction("Start Live Protection","Set up explicit microphone-based monitoring."){nav.navigate(Route.Live)} }; item { PrimaryAction("Try Demo","Explore deterministic simulated warning scenarios.",Amber){nav.navigate(Route.Demo)} }; item { HorizontalDivider(color=SignalMuted.copy(alpha=.28f));Text("Manage",modifier=Modifier.padding(top=8.dp),color=SignalMuted) }; item { CompactAction("Analysis History"){nav.navigate(Route.History)} }; item { CompactAction("Privacy Centre"){nav.navigate(Route.Privacy)} }; item { CompactAction("Settings"){nav.navigate(Route.Settings)};Spacer(Modifier.height(24.dp)) } }
}

@Composable private fun UploadScreen(vm:VoxViewModel,nav:NavHostController) {
    val context=LocalContext.current; var unavailable by rememberSaveable { mutableStateOf(false) }; val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){ uri->uri?.let{vm.selectFile(context,it);unavailable=false} }
    PageScaffold("Upload recording",nav) { Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(16.dp)) { Text("Analyse a recording",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold); Text("Choose audio through Android's file picker. VoxIT does not request broad storage access.",color=SignalMuted); OutlinedButton(onClick={picker.launch(arrayOf("audio/*","application/ogg"))},modifier=Modifier.fillMaxWidth().height(54.dp)){Text("Choose audio file")}; vm.selectedFile?.let{FileCard(it)}?:InfoPanel("No recording selected"); Button(onClick={unavailable=true},enabled=vm.selectedFile!=null,modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Analyse Recording")};if(unavailable)InfoPanel("Detection model not installed yet.",Amber);OutlinedButton(onClick={nav.navigate(Route.Demo)},enabled=vm.selectedFile!=null,modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Demonstrate this file in Demo Mode")};Text("Demo Mode uses a preset simulation; it does not analyse the selected file.",color=SignalMuted,style=MaterialTheme.typography.bodySmall) } }
}

@Composable private fun LiveScreen(vm:VoxViewModel,nav:NavHostController) { var requested by rememberSaveable { mutableStateOf(false) }; PageScaffold("Live Protection",nav) { Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(15.dp)){Text("Explicit, on-device microphone monitoring",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);InfoPanel("Start only when you choose. Speakerphone is recommended for the clearest microphone input.");StatusRow("Microphone","Not started — permission is not requested on launch");StatusRow("Floating bubble",if(vm.bubbleEnabled)"Enabled in settings" else "Disabled");StatusRow("Timer","00:00 placeholder");Waveform(0,false);InfoPanel("Live audio engine will be added in Phase 3.",Amber);SectionTitle("Partial transcript");InfoPanel("Transcription model not installed");SectionTitle("Risk indicators");EmptyRiskCards();Button(onClick={requested=true},modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Start Protection")};if(requested)Text("Live Protection is not available until the Phase 3 engine is integrated. No microphone was started.",color=Amber);OutlinedButton(onClick={},modifier=Modifier.fillMaxWidth().height(52.dp)){Text("Stop Protection")} } } }

@Composable private fun DemoScreen(vm:VoxViewModel,nav:NavHostController) {
    var frame by rememberSaveable { mutableIntStateOf(0) };var running by rememberSaveable{mutableStateOf(true)};var showWarning by rememberSaveable{mutableStateOf(false)};val scenario=vm.selectedScenario
    LaunchedEffect(running,scenario.name){while(running){delay(1700);frame=(frame+1)%scenario.frames.size}};val point=scenario.frames[frame];if(showWarning)WarningDialog(true,{showWarning=false},{running=false;showWarning=false})
    PageScaffold("Demo call",nav){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(13.dp)){DemoBadge();Text(scenario.name,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text(scenario.description,color=SignalMuted);Column(verticalArrangement=Arrangement.spacedBy(6.dp)){DemoScenario.scenarios.chunked(2).forEach { row -> Row(horizontalArrangement=Arrangement.spacedBy(6.dp),modifier=Modifier.fillMaxWidth()){row.forEach { option -> FilterChip(selected=option.name==scenario.name,onClick={vm.selectedScenario=option;frame=0},label={Text(option.name, maxLines=1, overflow=TextOverflow.Ellipsis)},modifier=Modifier.weight(1f)) } } }};Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){scenario.frames.indices.forEach{index->Box(Modifier.weight(1f).height(5.dp).clip(CircleShape).background(if(index<=frame)riskColor(point.risk.warningLevel) else SignalMuted.copy(.25f)))}};Waveform(frame,running);StatusRow("Signal",if(point.speaking)"Speech detected" else "Silence / listening");StatusRow("Audio quality",point.risk.audioQuality.label());TranscriptPreview(point.text,point.suspicious){nav.navigate(Route.Transcript)};RiskCards(point.risk){nav.navigate(Route.Result)};EvidencePanel(point.risk.evidence);if(point.risk.warningLevel!=WarningLevel.LOW)Button(onClick={showWarning=true},modifier=Modifier.fillMaxWidth().height(50.dp)){Text("Review warning guidance")};Row(horizontalArrangement=Arrangement.spacedBy(10.dp),modifier=Modifier.fillMaxWidth()){OutlinedButton(onClick={running=!running},modifier=Modifier.weight(1f).height(50.dp)){Text(if(running)"Pause demo" else "Continue Monitoring")};OutlinedButton(onClick={running=false},modifier=Modifier.weight(1f).height(50.dp)){Text("Stop Monitoring")}};OutlinedButton(onClick={showWarning=true},modifier=Modifier.fillMaxWidth().height(50.dp)){Text("Verify Caller")};Button(onClick={running=false},modifier=Modifier.fillMaxWidth().height(52.dp)){Text("End Demo Call")};Text("Ends only this in-app simulated call. It cannot end a cellular call.",color=SignalMuted,style=MaterialTheme.typography.bodySmall)}}
}

@Composable private fun ResultScreen(scenario:DemoScenario,nav:NavHostController)=PageScaffold("Analysis result",nav){val risk=scenario.frames.last().risk;Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){DemoBadge();Text(scenario.name,style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);WarningHeader(risk.warningLevel,risk.confidence);RiskCards(risk,{});Detail("Audio quality",risk.audioQuality.label());Detail("Speech duration","${risk.speechDurationSeconds} seconds");Detail("Detector mode","Demo Mode — simulated result");Detail("Model version","Demo timeline v1");SectionTitle("Evidence");EvidencePanel(risk.evidence);SectionTitle("Limitations");InfoPanel("Prototype interface thresholds only: 0–34 Low indication, 35–69 Uncertain—verify caller, 70–100 High indication. These are not scientific guarantees.");OutlinedButton(onClick={nav.navigate(Route.Transcript)},modifier=Modifier.fillMaxWidth().height(50.dp)){Text("Open simulated transcript")}}}

@Composable private fun TranscriptScreen(scenario:DemoScenario,nav:NavHostController){var deleted by rememberSaveable{mutableStateOf(false)};var selected by rememberSaveable{mutableIntStateOf(-1)};PageScaffold("Transcript",nav){Column(Modifier.fillMaxSize().padding(20.dp)){DemoBadge();Spacer(Modifier.height(12.dp));Text("Simulated transcript",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);Text("Demo content • supports English, Hindi, Hinglish and mixed-language segments.",color=SignalMuted,style=MaterialTheme.typography.bodySmall);Spacer(Modifier.height(12.dp));if(deleted)InfoPanel("Transcript deleted from this demo session.") else LazyColumn(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(8.dp)){items(scenario.transcript.withIndex().toList()){(index,segment)->val active=index==selected;Card(colors=CardDefaults.cardColors(containerColor=if(segment.suspicious)AlertRed.copy(.17f) else MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth().clickable{selected=index}.semantics{contentDescription="Transcript at ${segment.timestamp}: ${segment.text}"}){Column(Modifier.padding(14.dp)){Text("${segment.timestamp}  •  ${segment.language}${if(segment.confirmed)"  •  confirmed" else "  •  partial"}",color=SignalMuted,style=MaterialTheme.typography.labelSmall);Spacer(Modifier.height(5.dp));Text(segment.text,fontWeight=if(active||segment.suspicious)FontWeight.SemiBold else FontWeight.Normal);if(segment.suspicious)Text("Suspicious phrase",color=AlertRed,style=MaterialTheme.typography.labelSmall)}}}};OutlinedButton(onClick={deleted=true},modifier=Modifier.fillMaxWidth().height(50.dp),enabled=!deleted){Text("Delete transcript")};Spacer(Modifier.height(8.dp));Text("Real Mode: Transcription model not installed",color=SignalMuted,style=MaterialTheme.typography.bodySmall)}}}

@Composable private fun HistoryScreen(nav:NavHostController)=PageScaffold("Analysis History",nav){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){DemoBadge();Text("Demonstration history",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);DemoScenario.scenarios.take(3).forEachIndexed{index,scenario->val r=scenario.frames.last().risk;Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(15.dp),verticalArrangement=Arrangement.spacedBy(5.dp)){Text(scenario.name,fontWeight=FontWeight.SemiBold);Text("SIMULATED • Demo call • Today, ${10+index}:2${index} • ${r.speechDurationSeconds}s",color=SignalMuted,style=MaterialTheme.typography.bodySmall);Text("${r.warningLevel.title()}  |  Manipulation ${r.manipulation}  |  Mismatch ${r.speakerMismatch}  |  Scam ${r.scamRisk}",color=riskColor(r.warningLevel));Text("Model: Demo timeline v1",color=SignalMuted,style=MaterialTheme.typography.bodySmall)}}};InfoPanel("Real analysis history will appear here when on-device models are integrated.")}}

@Composable private fun PrivacyScreen(nav:NavHostController,phase2ViewModel:com.voxit.app.phase2.Phase2ViewModel)=PageScaffold("Privacy Centre",nav){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Text("Your audio deserves restraint.",style=MaterialTheme.typography.headlineSmall,fontWeight=FontWeight.Bold);PrivacyPoint("Local by default","Uploaded and explicitly started live processing stays on this device. Voice-integrity inference never uploads audio, features, or results.");PrivacyPoint("No silent recording","Live Protection starts only after you tap Start and grant microphone access. A foreground notification and microphone indicator remain visible.");PrivacyPoint("No raw live-audio storage","PCM stays in a bounded memory buffer, is never written to disk or uploaded, and is cleared when the session stops.");PrivacyPoint("Transcript control","Live transcripts are not saved or uploaded. Temporary transcript and risk state is deleted on Stop.");PrivacyPoint("Contextual permissions","Microphone and notification permissions are requested only when starting Live Protection. Overlay permission is requested separately only for the optional bubble.");PrivacyPoint("Android limitation","Protected cellular and VoIP call audio may be silent, blocked, or limited. VoxIT cannot claim both participants were captured. Speakerphone support is device-dependent and experimental.");PrivacyPoint("Model storage","Imported transcription and AASIST-L integrity models stay in separate app-private directories. Manage the integrity model from Upload Recording. Deleting an analysis clears its in-memory result and transcript.");ModelManagementPanel(phase2ViewModel);InfoPanel("The acoustic model is experimental, can make false positive and false negative errors, and does not prove that a person or call is genuine or fraudulent. No AccessibilityService, call-log, SMS, contacts, hidden monitoring, call control, analytics, or audio upload is used.",Amber);Button(onClick={phase2ViewModel.reset()},modifier=Modifier.fillMaxWidth().height(50.dp)){Text("Delete Uploaded-Audio Session Data")}}}

@Composable private fun SettingsScreen(vm:VoxViewModel,nav:NavHostController,phase2ViewModel:com.voxit.app.phase2.Phase2ViewModel)=PageScaffold("Settings",nav){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(20.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){ToggleRow("Demo Mode","Show simulation affordances on Home",vm.demoMode){vm.demoMode=it};ToggleRow("Notifications","Allow contextual alert notifications; the foreground-service status remains required",vm.notificationEnabled){vm.notificationEnabled=it};ToggleRow("Vibration","Vibrate only for gated live conversation warnings",vm.vibrationEnabled){vm.vibrationEnabled=it};ToggleRow("Floating bubble preference","Ask for separate overlay permission when Live Protection starts",vm.bubbleEnabled){vm.bubbleEnabled=it};ToggleRow("Save transcript","Off by default. Phase 3 live transcripts are temporary only.",vm.saveTranscript){vm.saveTranscript=false};SectionTitle("Alert threshold: ${vm.alertThreshold}");Slider(value=vm.alertThreshold.toFloat(),onValueChange={vm.alertThreshold=it.toInt()},valueRange=35f..90f);Text("Select the exact English or Hindi model below. Live Protection loads that persisted model ID at the start of its next session.",color=SignalMuted);ModelManagementPanel(phase2ViewModel);HorizontalDivider(color=SignalMuted.copy(.3f));Text("Voice-integrity model management and provenance are available from Upload Recording. Acoustic results are processed locally, not saved by default, and are never merged invisibly with transcript scam risk.",color=SignalMuted);CompactAction("Privacy settings"){nav.navigate(Route.Privacy)};CompactAction("Voice-integrity model information"){nav.navigate(Route.Upload)};CompactAction("App limitations"){nav.navigate(Route.Privacy)};Button(onClick={phase2ViewModel.reset()},modifier=Modifier.fillMaxWidth().height(50.dp)){Text("Delete uploaded-audio session data")}}}

@OptIn(ExperimentalMaterial3Api::class) @Composable private fun PageScaffold(title:String,nav:NavHostController?,content: @Composable () -> Unit)=Scaffold(containerColor=Navy,topBar={if(nav!=null)CenterAlignedTopAppBar(title={Text(title,color=Mist,fontWeight=FontWeight.SemiBold)},navigationIcon={OutlinedButton(onClick={nav.popBackStack()},modifier=Modifier.padding(start=8.dp)){Text("Back")}},colors=TopAppBarDefaults.centerAlignedTopAppBarColors(containerColor=Navy))}){padding->Box(Modifier.padding(padding)){content()}}

@Composable private fun Wordmark(size:androidx.compose.ui.unit.TextUnit)=Row(verticalAlignment=Alignment.Top){Text("Vox",color=Mist,fontWeight=FontWeight.Bold,fontSize=size);Text("IT",color=SignalBlue,fontWeight=FontWeight.ExtraBold,fontSize=size*.54f,modifier=Modifier.padding(top=1.dp))}
@Composable private fun ShieldMark(modifier:Modifier=Modifier)=Box(modifier.clip(RoundedCornerShape(26.dp)).background(SignalBlue.copy(.12f)).border(1.dp,SignalBlue,RoundedCornerShape(26.dp)),contentAlignment=Alignment.Center){Canvas(Modifier.size(58.dp).semantics{contentDescription="VoxIT shield and voice signal"}){drawCircle(SignalBlue,radius=size.minDimension/2.2f,style=Stroke(width=4.dp.toPx()));repeat(5){i->val x=size.width*(.20f+i*.15f);val h=size.height*(.20f+(i%3)*.12f);drawLine(SignalBlue,Offset(x,size.height/2-h),Offset(x,size.height/2+h),strokeWidth=3.dp.toPx(),cap=StrokeCap.Round)}}}
@Composable private fun DemoBadge()=Text("DEMO MODE – SIMULATED RESULT",color=Navy,fontWeight=FontWeight.Bold,fontSize=12.sp,modifier=Modifier.clip(RoundedCornerShape(8.dp)).background(Amber).padding(horizontal=10.dp,vertical=6.dp).semantics{contentDescription="Demo Mode simulated result"})
@Composable private fun StatusPill(text:String,color:Color)=Text(text,color=Navy,fontSize=12.sp,fontWeight=FontWeight.SemiBold,modifier=Modifier.clip(CircleShape).background(color).padding(horizontal=10.dp,vertical=6.dp))
@Composable private fun InfoPanel(text:String,emphasis:Color=SignalBlue)=Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth().border(1.dp,emphasis.copy(.28f),RoundedCornerShape(12.dp))){Text(text,modifier=Modifier.padding(14.dp),color=Mist)}
@Composable private fun PrivacyPoint(title:String,description:String)=Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(15.dp)){Text(title,fontWeight=FontWeight.SemiBold);Spacer(Modifier.height(4.dp));Text(description,color=SignalMuted)}}
@Composable private fun PrimaryAction(title:String,detail:String,accent:Color=SignalBlue,onClick:()->Unit)=Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth().clickable(onClick=onClick).border(1.dp,accent.copy(.35f),RoundedCornerShape(16.dp))){Column(Modifier.padding(18.dp)){Text(title,fontSize=18.sp,fontWeight=FontWeight.SemiBold,color=accent);Spacer(Modifier.height(5.dp));Text(detail,color=SignalMuted)}}
@Composable private fun CompactAction(title:String,onClick:()->Unit)=OutlinedButton(onClick=onClick,modifier=Modifier.fillMaxWidth().height(48.dp)){Text(title,modifier=Modifier.fillMaxWidth(),textAlign=TextAlign.Start)}
@Composable private fun StatusRow(label:String,value:String)=Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,fontWeight=FontWeight.SemiBold);Text(value,color=SignalMuted,modifier=Modifier.widthIn(max=210.dp),textAlign=TextAlign.End)}
@Composable private fun SectionTitle(text:String)=Text(text,color=SignalBlue,fontWeight=FontWeight.SemiBold,fontSize=14.sp)
@Composable private fun Detail(label:String,value:String)=Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(label,color=SignalMuted);Text(value,fontWeight=FontWeight.SemiBold,textAlign=TextAlign.End)}
@Composable private fun Waveform(frame:Int,active:Boolean)=Canvas(Modifier.fillMaxWidth().height(102.dp).clip(RoundedCornerShape(16.dp)).background(MaterialTheme.colorScheme.surfaceVariant).semantics{contentDescription=if(active)"Animated simulated audio waveform" else "Inactive waveform placeholder"}){val center=size.height/2;val bars=28;repeat(bars){i->val pulse=if(active)((i*7+frame*11)%23)/23f else .12f;val h=10.dp.toPx()+pulse*size.height*.38f;val x=(i+.5f)*size.width/bars;drawLine(if(active)SignalBlue else SignalMuted,Offset(x,center-h),Offset(x,center+h),strokeWidth=4.dp.toPx(),cap=StrokeCap.Round)}}
@Composable private fun TranscriptPreview(text:String,suspicious:Boolean,onOpen:()->Unit)=Card(colors=CardDefaults.cardColors(containerColor=if(suspicious)AlertRed.copy(.17f) else MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth().clickable(onClick=onOpen)){Column(Modifier.padding(14.dp)){SectionTitle("Live transcript • simulated");Spacer(Modifier.height(6.dp));Text(text,maxLines=3,overflow=TextOverflow.Ellipsis,fontWeight=if(suspicious)FontWeight.SemiBold else FontWeight.Normal);if(suspicious)Text("Suspicious sentence highlighted",color=AlertRed,style=MaterialTheme.typography.labelSmall)}}
@Composable private fun EmptyRiskCards()=Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){listOf("Voice manipulation","Speaker mismatch","Scam risk").forEach{Card(Modifier.weight(1f),colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant)){Text("$it\nNot available",modifier=Modifier.padding(10.dp),color=SignalMuted,style=MaterialTheme.typography.labelSmall)}}}
@Composable private fun RiskCards(risk:RiskResult,onOpen:()->Unit)=Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){ScoreCard("Voice manipulation",risk.manipulation,onOpen);ScoreCard("Speaker mismatch",risk.speakerMismatch,onOpen);ScoreCard("Scam risk",risk.scamRisk,onOpen)}
@Composable private fun RowScope.ScoreCard(label:String,score:Int,onOpen:()->Unit){val level=levelOf(score);Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.weight(1f).clickable(onClick=onOpen)){Column(Modifier.padding(10.dp)){Text(label,color=SignalMuted,fontSize=11.sp,lineHeight=14.sp);Text("$score",fontSize=28.sp,fontWeight=FontWeight.Bold,color=riskColor(level));Text(level.title(),fontSize=10.sp,color=riskColor(level))}}}
@Composable private fun WarningHeader(level:WarningLevel,confidence:Int)=Card(colors=CardDefaults.cardColors(containerColor=riskColor(level).copy(.16f)),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text("${level.title()} warning level",color=riskColor(level),fontWeight=FontWeight.Bold,fontSize=19.sp);Text("Confidence: $confidence% • Demo result",color=Mist)}}
@Composable private fun EvidencePanel(items:List<EvidenceReason>)=Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){if(items.isEmpty())Text("No simulated evidence in this timeline step.",color=SignalMuted)else items.forEach{Text("${it.title}: ${it.detail}",color=Mist)}}}
@Composable private fun ToggleRow(title:String,detail:String,checked:Boolean,onChanged:(Boolean)->Unit)=Row(Modifier.fillMaxWidth().padding(vertical=6.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(title,fontWeight=FontWeight.SemiBold);Text(detail,color=SignalMuted,style=MaterialTheme.typography.bodySmall)};Switch(checked=checked,onCheckedChange=onChanged)}
@Composable private fun WarningDialog(demo:Boolean,onDismiss:()->Unit,onEndDemo:()->Unit)=AlertDialog(onDismissRequest=onDismiss,title={Text("Verify before you share")},text={Text("Suspicious voice or conversation patterns were detected. This is a warning, not proof. Avoid sharing OTPs, passwords, PINs or payment information. Verify the caller using an official number.")},confirmButton={Button(onClick=onDismiss){Text("Continue Monitoring")}},dismissButton={Column(horizontalAlignment=Alignment.End){OutlinedButton(onClick=onDismiss){Text("Stop Monitoring")};OutlinedButton(onClick=onDismiss){Text("Verify Caller")};OutlinedButton(onClick=onDismiss){Text("Open Phone Controls")};if(demo)Button(onClick=onEndDemo){Text("End Demo Call")}}})

private data class FileInfo(val name:String,val size:String,val type:String)
private fun Context.fileInfo(uri:Uri):FileInfo{var name="Selected audio";var size="Size unavailable";contentResolver.query(uri,arrayOf(OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE),null,null,null)?.use{if(it.moveToFirst()){name=it.getString(0)?:name;val bytes=it.getLong(1);if(bytes>=0)size="${bytes/1024} KB"}};return FileInfo(name,size,contentResolver.getType(uri)?:"Audio file")}
@Composable private fun FileCard(file:FileInfo)=Card(colors=CardDefaults.cardColors(containerColor=MaterialTheme.colorScheme.surfaceVariant),modifier=Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp)){Text(file.name,fontWeight=FontWeight.SemiBold);Text("${file.type} • ${file.size}",color=SignalMuted,style=MaterialTheme.typography.bodySmall)}}
private fun AudioQuality.label()=when(this){AudioQuality.GOOD->"Good";AudioQuality.NOISY->"Noisy";AudioQuality.INSUFFICIENT->"Insufficient audio";AudioQuality.UNKNOWN->"Unknown"}
private fun WarningLevel.title()=when(this){WarningLevel.LOW->"Low indication";WarningLevel.UNCERTAIN->"Uncertain — verify";WarningLevel.HIGH->"High indication"}
private fun levelOf(score:Int)=when(score){in 0..34->WarningLevel.LOW;in 35..69->WarningLevel.UNCERTAIN;else->WarningLevel.HIGH}
private fun riskColor(level:WarningLevel)=when(level){WarningLevel.LOW->SafeGreen;WarningLevel.UNCERTAIN->Amber;WarningLevel.HIGH->AlertRed}

private data class DemoPoint(val speaking:Boolean,val text:String,val suspicious:Boolean,val risk:RiskResult)
private data class DemoScenario(val name:String,val description:String,val frames:List<DemoPoint>,val transcript:List<TranscriptSegment>){companion object{
    private fun r(m:Int,s:Int,c:Int,confidence:Int,quality:AudioQuality=AudioQuality.GOOD,evidence:List<EvidenceReason> = emptyList())=RiskResult(m,s,c,confidence,levelOf(maxOf(m,s,c)),quality,38,evidence)
    private fun e(title:String,detail:String)=EvidenceReason(title,detail)
    private fun transcript(vararg rows:Triple<String,String,Boolean>)=rows.mapIndexed{i,row->TranscriptSegment("00:${(i*8+3).toString().padStart(2,'0')}",row.second,if(i%2==0)"English" else "Hinglish",confirmed=i<2,suspicious=row.third)}
    val scenarios=listOf(
      DemoScenario("Trusted human voice","A calm baseline scenario with no simulated warning evidence.",listOf(DemoPoint(true,"Hi, I called to confirm our meeting tomorrow.",false,r(12,8,10,82)),DemoPoint(false,"",false,r(8,6,8,85)),DemoPoint(true,"Thank you, see you then.",false,r(10,7,9,86))),transcript(Triple("","Hi, I called to confirm our meeting tomorrow.",false),Triple("","Haan, calendar mein add kar diya.",false),Triple("","Thank you, see you then.",false))),
      DemoScenario("Noisy or insufficient audio","The timeline demonstrates an unusable input, not a risk conclusion.",listOf(DemoPoint(true,"[background traffic and clipped speech]",false,r(0,0,0,20,AudioQuality.NOISY,listOf(e("Audio quality","Background noise prevents a reliable assessment.")))),DemoPoint(false,"[silence]",false,r(0,0,0,12,AudioQuality.INSUFFICIENT,listOf(e("Insufficient speech","Collect more clear speech before assessing.")))),DemoPoint(true,"Could you repeat that?",false,r(0,0,0,25,AudioQuality.NOISY))),transcript(Triple("","[unclear audio]",false),Triple("","Could you repeat that?",false))),
      DemoScenario("Suspected AI-generated voice","Preset synthetic-speech indicators rise, then soften when clean speech changes.",listOf(DemoPoint(true,"Your account needs immediate verification.",true,r(43,12,40,71,evidence=listOf(e("Voice pattern","Simulated unusually regular prosody.")))),DemoPoint(true,"Please open the secure link now.",true,r(78,18,62,84,evidence=listOf(e("Voice pattern","Simulated spectral consistency."),e("Urgency language","Pressure to act immediately.")))),DemoPoint(false,"",false,r(58,14,44,78,evidence=listOf(e("Voice pattern","Simulation remains uncertain."))))),transcript(Triple("","Your account needs immediate verification.",true),Triple("","Please open the secure link now.",true),Triple("","Main abhi busy hoon.",false))),
      DemoScenario("Suspected voice clone","Preset voice mismatch evidence is shown as a caution, never proof of identity.",listOf(DemoPoint(true,"It's me. I need a quick favour.",false,r(32,46,35,68,evidence=listOf(e("Speaker match","Simulated mismatch against an enrolled voice.")))),DemoPoint(true,"Can you send the code I just received?",true,r(61,82,72,88,evidence=listOf(e("Speaker match","Simulated voice-print mismatch."),e("Sensitive request","One-time code requested.")))),DemoPoint(false,"",false,r(48,66,54,78,evidence=listOf(e("Speaker match","Verify identity through another channel."))))),transcript(Triple("","It's me. I need a quick favour.",false),Triple("","Can you send the code I just received?",true))),
      DemoScenario("Suspicious scam conversation","The warning comes from simulated conversation context rather than a voice claim.",listOf(DemoPoint(true,"Your KYC will expire today, sir.",true,r(14,10,56,76,evidence=listOf(e("Scam language","Simulated deadline pressure.")))),DemoPoint(true,"Share the OTP so I can secure the account.",true,r(18,14,91,91,evidence=listOf(e("Scam language","OTP requested."),e("Urgency language","Action requested without verification.")))),DemoPoint(false,"",false,r(10,8,67,82,evidence=listOf(e("Scam language","Use an official number to verify."))))),transcript(Triple("","Your KYC will expire today, sir.",true),Triple("","Share the OTP so I can secure the account.",true))),
      DemoScenario("High combined risk","A deterministic combined-risk showcase with scores that can rise and fall.",listOf(DemoPoint(true,"This is bank security. Act now.",true,r(55,62,72,83,evidence=listOf(e("Voice pattern","Simulated manipulation indicator."),e("Scam language","Urgent authority claim.")))),DemoPoint(true,"Give me the PIN and OTP before the account locks.",true,r(91,88,96,94,evidence=listOf(e("Voice pattern","Simulated synthetic-speech indicator."),e("Speaker match","Simulated mismatch."),e("Sensitive request","PIN and OTP requested.")))),DemoPoint(false,"",false,r(63,69,71,87,evidence=listOf(e("Combined signal","Warning persists; verify caller independently."))))),transcript(Triple("","This is bank security. Act now.",true),Triple("","Give me the PIN and OTP before the account locks.",true),Triple("","I will call the official number.",false)))
    )
}}
